# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CGPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ip', models.GenericIPAddressField()),
                ('university', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=128)),
                ('university', models.CharField(max_length=4)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=256)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ip', models.GenericIPAddressField()),
                ('university', models.CharField(max_length=16)),
            ],
        ),
    ]
