# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgpa',
            name='university',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='grade',
            name='university',
            field=models.CharField(max_length=16),
        ),
    ]
